### ISSUE TITLE
Error on Linux Systems - CLI

### ISSUE THREAD

**Issue by LetDowntoVoid** [mytja/PloudOS-API#4]
There is this error when we use it on a Linux CLI system

```py
Traceback (most recent call last):
  File "/home/runner/JgsBotNew/venv/lib/python3.10/site-packages/nextcord/client.py", line 512, in _run_event
    await coro(*args, **kwargs)
  File "main.py", line 716, in on_application_command_error
    raise error
  File "/home/runner/JgsBotNew/venv/lib/python3.10/site-packages/nextcord/application_command.py", line 906, in invoke_callback_with_hooks
    await self(interaction, *args, **kwargs)
  File "main.py", line 1662, in mc_start
    info = await ploudos.get_server_info()
  File "/home/runner/JgsBotNew/venv/lib/python3.10/site-packages/ploudos/ploudos.py", line 60, in get_server_info
    return r.json()
  File "/home/runner/JgsBotNew/venv/lib/python3.10/site-packages/httpx/_models.py", line 756, in json
    return jsonlib.loads(self.text, **kwargs)
  File "/nix/store/hd4cc9rh83j291r5539hkf6qd8lgiikb-python3-3.10.8/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/nix/store/hd4cc9rh83j291r5539hkf6qd8lgiikb-python3-3.10.8/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/nix/store/hd4cc9rh83j291r5539hkf6qd8lgiikb-python3-3.10.8/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 2 column 1 (char 1)
```

**Comment by mytja** [comment]
Given that last commit was exactly 1 year ago, I think this should be deprecated.
I'm not using PloudOS anymore, so I cannot maintain this anymore.
